~dirt.loadSoundFiles("/home/mint/Dokumente/Samples/DrumPadBeats/minima/SongZip")
~dirt.loadSoundFiles("/home/mint/Dokumente/Samples/DrumPadBeats/t5d/Scene/")
~dirt.loadSoundFiles("/home/mint/Dokumente/Samples/DrumPadBeats/h/Scene2/")
~dirt.loadSoundFiles("/home/mint/Dokumente/Samples/beatbox/Bigbeard Drums/REALDRUMS")
~dirt.loadSoundFiles("/home/mint/Dokumente/Samples/dskmusic/DirectWave/DSK Music - Analog Synth sounds/Synths/*")
~dirt.loadSoundFiles("/home/mint/Dokumente/Samples/HexLoops.House.FREE.Drops/Kit02_C_128bpm")
~dirt.loadSoundFiles("/home/mint/Dokumente/Samples/TASTERS/*")
